In [76]:
import pandas as pd
import numpy as np
import category_encoders
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import category_encoders as ce
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
car_data_df = pd.read_csv('../input/car-evaluation-data-set/car_evaluation.csv')
car_data_df=car_data_df.rename(columns={'vhigh':'buying_price','vhigh.1':'maint','2':'num_doors','2.1':'num_persons','small':'lug_boot','low':'safety','unacc':'decision'})

In [60]:
features = ['buying_price','maint','num_doors','num_persons','lug_boot','safety']
X = car_data_df[features]

In [61]:
target = ['decision']
Y = car_data_df[target]

In [62]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,train_size=0.9)


In [64]:
ordinal_encoder = ce.OrdinalEncoder(cols=['buying_price', 'maint', 'num_doors', 'num_persons', 'lug_boot', 'safety'])
X_train = ordinal_encoder.fit_transform(X_train)
X_test = ordinal_encoder.transform(X_test)

In [75]:
clf = DecisionTreeClassifier(criterion='gini',max_depth=10)
clf.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10)

In [73]:
Y_pred = clf.predict(X_test)

In [74]:
accuracy_score(Y_test,Y_pred)

0.9710982658959537

In [77]:
cm = confusion_matrix(Y_test, Y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[ 45   0   2   1]
 [  1   7   0   1]
 [  0   0 112   0]
 [  0   0   0   4]]


In [79]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

         acc       0.98      0.94      0.96        48
        good       1.00      0.78      0.88         9
       unacc       0.98      1.00      0.99       112
       vgood       0.67      1.00      0.80         4

    accuracy                           0.97       173
   macro avg       0.91      0.93      0.91       173
weighted avg       0.97      0.97      0.97       173

